#!/bin/bash

# Exit if any operation fails
set -e

# Move to project root
cd "$(dirname "$0")/.."

# Generate plist syntax
echo "==> Converting YAML syntax to plist"
script/yaml-to-plist "syntaxes/Asciidoctor.YAML-tmLanguage" "syntaxes/Asciidoctor.tmLanguage"

# Build extension
echo "==> Installing local dependencies"
npm install

# Check status of vsce and typescript dependencies
unset deps
npm list -g vsce &>/dev/null || deps+=("vsce")
npm list -g typescript &>/dev/null || deps+=("typescript")
if [[ -n $deps ]] ; then
  echo "==> Installing global dependencies [needs sudo]"
  sudo npm install -g ${deps[@]}
fi

# Package extension
echo "==> Packaging extension"
rm -f *.vsix
vsce package

if [[ $1 == install ]] ; then
  echo "==> Installing extension"
  code --install-extension *.vsix
fi
