#!/bin/bash

# Exit if any operation fails
exitdialog() {
  echo -e "==> \033[0;31m\033[1mERROR\033[0m: build aborted"
  exit ${1:-1}
}

# Move to project root
cd "$(dirname "$0")/.."

# Generate plist syntax
echo "==> Converting YAML syntax to plist"
[[ ! -x script/yaml-to-plist ]] && chmod +x script/yaml-to-plist
script/yaml-to-plist "syntaxes/Asciidoctor.YAML-tmLanguage" "syntaxes/Asciidoctor.tmLanguage" || exitdialog $?

# Build extension
echo "==> Installing local dependencies"
npm install || exitdialog $?

# Check status of vsce and typescript dependencies
unset deps
npm list -g vsce &>/dev/null || deps+=("vsce")
npm list -g typescript &>/dev/null || deps+=("typescript")
if [[ -n $deps ]] ; then
  echo "==> Installing global dependencies [needs sudo]"
  sudo npm install -g ${deps[@]} || exitdialog $?
fi

# Package extension
echo "==> Packaging extension"
rm -f *.vsix
vsce package || exitdialog

if [[ $1 == install ]] ; then
  echo "==> Installing extension"
  code --install-extension *.vsix || exitdialog $?
fi
