import parseResourceId from '@antora/content-classifier/util/parse-resource-id'
import type { AntoraResourceContext } from './antoraContext.js'

export interface SiteManifestPage {
  path: string
  url: string
  title?: string
  navtitle?: string
  module?: string
  alias?: { ref: string; url: string }
}

export interface SiteManifestVersion {
  url: string
  pages: SiteManifestPage[]
}

export interface SiteManifestComponent {
  title?: string
  latest: string
  versions: { [version: string]: SiteManifestVersion }
}

export interface SiteManifest {
  $id?: string
  generated?: string
  url: string
  components: { [name: string]: SiteManifestComponent }
}

/** A page resolved from a {@link SiteManifest}, not backed by any local file. */
export interface RemoteResource {
  component: string
  version: string
  module: string
  path: string
  /** Absolute URL of the published page (resolved against the manifest's site `url`). */
  url: string
  title?: string
  navtitle?: string
}

const ABSOLUTE_URL_RX = /^[a-z][a-z0-9+.-]*:\/\//i

export function isRemoteUrl(value: string): boolean {
  return ABSOLUTE_URL_RX.test(value)
}

/**
 * Parse a site-manifest.json document (as generated by Antora Atlas,
 * https://schemas.antora.org/site-manifest/1-0-0/draft-01). Returns `undefined`
 * when the input is not valid JSON or does not look like a site manifest, so
 * callers can log a warning naming the offending file instead of throwing.
 */
export function parseSiteManifest(raw: string): SiteManifest | undefined {
  let data: unknown
  try {
    data = JSON.parse(raw)
  } catch {
    return undefined
  }
  if (
    data === null ||
    typeof data !== 'object' ||
    typeof (data as { components?: unknown }).components !== 'object' ||
    (data as { components?: unknown }).components === null
  ) {
    return undefined
  }
  return data as SiteManifest
}

function componentVersionKey(component: string, version: string): string {
  return `${component}@${version}`
}

function pageKey(
  component: string,
  version: string,
  module: string,
  relative: string,
): string {
  return `${componentVersionKey(component, version)}:${module}:${relative}`
}

/**
 * A read-only catalogue of the pages listed in a site-manifest.json, indexed
 * for O(1) lookup by resource id coordinates. Only the `page` family is
 * covered: the manifest carries no information about images, examples or
 * partials, so `xref` is the only macro this catalogue can usefully resolve.
 */
export class RemoteAntoraCatalog {
  private readonly pagesByKey = new Map<string, RemoteResource>()
  private readonly latestByComponent = new Map<string, string>()
  private readonly siteUrl: string

  constructor(manifest: SiteManifest) {
    this.siteUrl = manifest.url ?? ''
    for (const [component, componentDescriptor] of Object.entries(
      manifest.components ?? {},
    )) {
      if (componentDescriptor.latest !== undefined) {
        this.latestByComponent.set(component, componentDescriptor.latest)
      }
      for (const [version, versionDescriptor] of Object.entries(
        componentDescriptor.versions ?? {},
      )) {
        for (const page of versionDescriptor.pages ?? []) {
          const module = page.module ?? 'ROOT'
          const key = pageKey(component, version, module, page.path)
          this.pagesByKey.set(key, {
            component,
            version,
            module,
            path: page.path,
            url: this.resolveUrl(page.url),
            title: page.title,
            navtitle: page.navtitle,
          })
        }
      }
    }
  }

  private resolveUrl(pageUrl: string): string {
    if (isRemoteUrl(pageUrl)) {
      return pageUrl
    }
    if (!this.siteUrl) {
      return pageUrl
    }
    return `${this.siteUrl.replace(/\/+$/, '')}${pageUrl}`
  }

  /**
   * Resolve a contextual resource id spec (e.g. `2.0@cli:commands:page.adoc`)
   * against this catalogue. `excludeComponentVersions` — built from the local
   * content catalog — skips any component/version pair already known locally,
   * so a workspace copy of a component always wins over the manifest, which is
   * only a snapshot taken at generation time and may be stale.
   */
  public resolveResourceId(
    spec: string,
    ctx: AntoraResourceContext,
    defaultFamily: string,
    excludeComponentVersions: ReadonlySet<string>,
  ): RemoteResource | undefined {
    const id = parseResourceId(spec, ctx, defaultFamily, ['page'])
    if (!id || id.family !== 'page' || !id.component) {
      return undefined
    }
    const component = id.component
    let version = id.version
    if (version == null) {
      version = this.manifestLatest(component)
      if (version === undefined) {
        return undefined
      }
    }
    if (excludeComponentVersions.has(componentVersionKey(component, version))) {
      return undefined
    }
    const module = id.module || 'ROOT'
    return this.pagesByKey.get(pageKey(component, version, module, id.relative))
  }

  private manifestLatest(component: string): string | undefined {
    return this.latestByComponent.get(component)
  }

  /**
   * Every page known to this catalogue, excluding component/version pairs
   * already present in the local content catalog.
   */
  public findPages(
    excludeComponentVersions: ReadonlySet<string>,
  ): RemoteResource[] {
    return [...this.pagesByKey.values()].filter(
      (page) =>
        !excludeComponentVersions.has(
          componentVersionKey(page.component, page.version),
        ),
    )
  }
}
