name: Release
on:
  workflow_dispatch:
    inputs:
      release-version:
        description: Enter version to release (e.g., 2.0.1).
        required: true
      pre-release:
        description: Publish as a pre-release (Marketplace, Open VSX and GitHub).
        type: boolean
        default: false

run-name: Release ${{ inputs.release-version }}${{ inputs.pre-release && ' (pre-release)' || '' }} by @${{ github.actor }}
jobs:
  activate:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'asciidoctor' && github.event_name == 'workflow_dispatch'
    steps:
      - run: echo ok go
  perform:
    needs: activate
    runs-on: ubuntu-latest
    environment: releases
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version-file: 'package.json'
      - name: Install dependencies
        run: npm ci
      - name: Setup release environment
        run: |
          echo ${{ secrets[format('GH_TOKEN_{0}', github.actor)] }} | gh auth login --with-token
          echo RELEASE_VERSION=${{ github.event.inputs.release-version }} >> $GITHUB_ENV
          echo PRERELEASE=${{ github.event.inputs.pre-release }} >> $GITHUB_ENV
          echo RELEASE_VSCE_TOKEN=${{ secrets['VSCE_TOKEN'] }} >> $GITHUB_ENV
          echo RELEASE_OVSX_TOKEN=${{ secrets['OVSX_TOKEN'] }} >> $GITHUB_ENV
      - name: Build, tag, and publish extension
        run: ./release.sh
      - name: Announce release on Zulip
        uses: zulip/github-actions-zulip/send-message@v2
        with:
          email: ${{ secrets.ZULIP_USERNAME }}
          api-key: ${{ secrets.ZULIP_API_KEY }}
          organization-url: 'https://asciidoctor.zulipchat.com'
          to: '279652'
          type: 'stream'
          topic: 'releases'
          content: |
            Asciidoctor VS Code ${{ env.RELEASE_TAG }}${{ env.RELEASE_IS_PRERELEASE == 'true' && ' (pre-release)' || '' }} is out!

            https://github.com/asciidoctor/asciidoctor-vscode/releases/tag/${{ env.RELEASE_TAG }}
